#!/bin/sh
#
# Plugin to plot OpenVZ VE Stats
#
# by Rene Weselowski
# http://www.dead.at
#
# Mod by fortitou
# http://www.fortitou.be
#
# Parameters:
#
#       config   (required)
#       autoconf (optional - used by munin-config)
#
# $Log$
#
#%# family=auto
#%# capabilities=autoconf

ATTRIBUTE=`basename $0 | sed 's/^openvz_//g'`


if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo "graph_title $ATTRIBUTE"
        echo "graph_args --upper-limit 100 -l 0"
        echo "graph_scale no"
        echo "graph_vlabel $ATTRIBUTE %"
        echo "graph_category openvz"
        echo "graph_info This graph shows OpenVZ: $ATTRIBUTE"
        vzlist -a -H -o hostname | awk '{gsub(/\./,"_",$1)
        print("'$ATTRIBUTE'"$1".label "$1"\n" \
        "'$ATTRIBUTE'"$1".info '$ATTRIBUTE' for VE "$1"\n" \
        "'$ATTRIBUTE'"$1".warning 92\n" \
        "'$ATTRIBUTE'"$1".critical 98" \
        )}'
        exit 0
fi

vzlist -a -H -o hostname,$ATTRIBUTE,$ATTRIBUTE.s | awk '{ gsub(/\./,"_",$1)
 printf("%s %f\n", "'$ATTRIBUTE'"$1".value", $2*100/$3) }' 


exit 0

