#!/bin/bash
#
# Plugin to plot OpenVZ VE Stats
#

: << =cut

=head1 NAME

openvz_sh_ - Plugin to measure OpenVZ percentages of vzlist -L with attr.s and attr.h  
             See suggest for correct link values  

=head1 AUTHOR

Contributed by Rene Weselowski, mod by Bruno Félix

=head1 LICENSE

Unknown license

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

# Various tests
if [ ! -d /proc/vz ] ; then
	echo "This server does not seem to run OpenVZ"
	exit 1
fi

ATTRIBUTE=`basename $0 | sed 's/^openvz_sh_//g'`
if [ $ATTRIBUTE = `basename $0` ]; then
	ATTRIBUTE=`basename $0 | sed 's/^openvz_//g'`
fi

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "suggest" ]; then
        echo diskspace
        echo diskinodes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo "graph_title $ATTRIBUTE"
        echo "graph_args --upper-limit 100 -l 0"
        echo "graph_scale no"
        echo "graph_vlabel $ATTRIBUTE %"
        echo "graph_category openvz"
        echo "graph_info This graph shows OpenVZ: $ATTRIBUTE"
        vzlist -a -H -o hostname | awk '{gsub(/\./,"_",$1)
        print("'$ATTRIBUTE'"$1".label "$1"\n" \
        "'$ATTRIBUTE'"$1".info '$ATTRIBUTE' for VE "$1"\n" \
        "'$ATTRIBUTE'"$1".warning 92\n" \
        "'$ATTRIBUTE'"$1".critical 98" \
        )}'
        exit 0
fi


vzlist -a -H -o hostname,$ATTRIBUTE,$ATTRIBUTE.s | awk '{ gsub(/\./,"_",$1)
 	printf("%s %f\n", "'$ATTRIBUTE'"$1".value", $2*100/$3) }' 


exit 0

